name: Comment Workflow

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post a comment
        env:
          GH_TOKEN: ${{ secrets.Action token2 }}
        run: echo "This is a GitHub Actions comment workflow"
